[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
scrollstake = "7mDauA2UnGfJsy7TPQLRJT5wc5HbExaXMoicnxM2Dk96"

[programs.localnet]
scrollstake = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
